/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupabaseCallbackRouteImport } from './routes/supabaseCallback'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotpasswordRouteImport } from './routes/forgotpassword'
import { Route as EmailVerifyRouteImport } from './routes/emailVerify'
import { Route as _protectedRouteImport } from './routes/__protected'
import { Route as LandingPageRouteImport } from './routes/LandingPage'
import { Route as IndexRouteImport } from './routes/index'
import { Route as _protectedTutorRouteImport } from './routes/__protected.tutor'
import { Route as _protectedQuizzesRouteImport } from './routes/__protected.quizzes'
import { Route as _protectedNotesRouteImport } from './routes/__protected.notes'
import { Route as _protectedLibraryRouteImport } from './routes/__protected.library'
import { Route as _protectedQuizzesIndexRouteImport } from './routes/__protected.quizzes.index'
import { Route as _protectedNotesIndexRouteImport } from './routes/__protected.notes.index'
import { Route as _protectedQuizzesQuizIdRouteImport } from './routes/__protected.quizzes.$quizId'
import { Route as _protectedNotesNoteIdRouteImport } from './routes/__protected.notes.$noteId'

const SupabaseCallbackRoute = SupabaseCallbackRouteImport.update({
  id: '/supabaseCallback',
  path: '/supabaseCallback',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotpasswordRoute = ForgotpasswordRouteImport.update({
  id: '/forgotpassword',
  path: '/forgotpassword',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailVerifyRoute = EmailVerifyRouteImport.update({
  id: '/emailVerify',
  path: '/emailVerify',
  getParentRoute: () => rootRouteImport,
} as any)
const _protectedRoute = _protectedRouteImport.update({
  id: '/__protected',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingPageRoute = LandingPageRouteImport.update({
  id: '/LandingPage',
  path: '/LandingPage',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const _protectedTutorRoute = _protectedTutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => _protectedRoute,
} as any)
const _protectedQuizzesRoute = _protectedQuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => _protectedRoute,
} as any)
const _protectedNotesRoute = _protectedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => _protectedRoute,
} as any)
const _protectedLibraryRoute = _protectedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => _protectedRoute,
} as any)
const _protectedQuizzesIndexRoute = _protectedQuizzesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => _protectedQuizzesRoute,
} as any)
const _protectedNotesIndexRoute = _protectedNotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => _protectedNotesRoute,
} as any)
const _protectedQuizzesQuizIdRoute = _protectedQuizzesQuizIdRouteImport.update({
  id: '/$quizId',
  path: '/$quizId',
  getParentRoute: () => _protectedQuizzesRoute,
} as any)
const _protectedNotesNoteIdRoute = _protectedNotesNoteIdRouteImport.update({
  id: '/$noteId',
  path: '/$noteId',
  getParentRoute: () => _protectedNotesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/LandingPage': typeof LandingPageRoute
  '/emailVerify': typeof EmailVerifyRoute
  '/forgotpassword': typeof ForgotpasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/supabaseCallback': typeof SupabaseCallbackRoute
  '/library': typeof _protectedLibraryRoute
  '/notes': typeof _protectedNotesRouteWithChildren
  '/quizzes': typeof _protectedQuizzesRouteWithChildren
  '/tutor': typeof _protectedTutorRoute
  '/notes/$noteId': typeof _protectedNotesNoteIdRoute
  '/quizzes/$quizId': typeof _protectedQuizzesQuizIdRoute
  '/notes/': typeof _protectedNotesIndexRoute
  '/quizzes/': typeof _protectedQuizzesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/LandingPage': typeof LandingPageRoute
  '/emailVerify': typeof EmailVerifyRoute
  '/forgotpassword': typeof ForgotpasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/supabaseCallback': typeof SupabaseCallbackRoute
  '/library': typeof _protectedLibraryRoute
  '/tutor': typeof _protectedTutorRoute
  '/notes/$noteId': typeof _protectedNotesNoteIdRoute
  '/quizzes/$quizId': typeof _protectedQuizzesQuizIdRoute
  '/notes': typeof _protectedNotesIndexRoute
  '/quizzes': typeof _protectedQuizzesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/LandingPage': typeof LandingPageRoute
  '/__protected': typeof _protectedRouteWithChildren
  '/emailVerify': typeof EmailVerifyRoute
  '/forgotpassword': typeof ForgotpasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/supabaseCallback': typeof SupabaseCallbackRoute
  '/__protected/library': typeof _protectedLibraryRoute
  '/__protected/notes': typeof _protectedNotesRouteWithChildren
  '/__protected/quizzes': typeof _protectedQuizzesRouteWithChildren
  '/__protected/tutor': typeof _protectedTutorRoute
  '/__protected/notes/$noteId': typeof _protectedNotesNoteIdRoute
  '/__protected/quizzes/$quizId': typeof _protectedQuizzesQuizIdRoute
  '/__protected/notes/': typeof _protectedNotesIndexRoute
  '/__protected/quizzes/': typeof _protectedQuizzesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/LandingPage'
    | '/emailVerify'
    | '/forgotpassword'
    | '/login'
    | '/register'
    | '/supabaseCallback'
    | '/library'
    | '/notes'
    | '/quizzes'
    | '/tutor'
    | '/notes/$noteId'
    | '/quizzes/$quizId'
    | '/notes/'
    | '/quizzes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/LandingPage'
    | '/emailVerify'
    | '/forgotpassword'
    | '/login'
    | '/register'
    | '/supabaseCallback'
    | '/library'
    | '/tutor'
    | '/notes/$noteId'
    | '/quizzes/$quizId'
    | '/notes'
    | '/quizzes'
  id:
    | '__root__'
    | '/'
    | '/LandingPage'
    | '/__protected'
    | '/emailVerify'
    | '/forgotpassword'
    | '/login'
    | '/register'
    | '/supabaseCallback'
    | '/__protected/library'
    | '/__protected/notes'
    | '/__protected/quizzes'
    | '/__protected/tutor'
    | '/__protected/notes/$noteId'
    | '/__protected/quizzes/$quizId'
    | '/__protected/notes/'
    | '/__protected/quizzes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LandingPageRoute: typeof LandingPageRoute
  _protectedRoute: typeof _protectedRouteWithChildren
  EmailVerifyRoute: typeof EmailVerifyRoute
  ForgotpasswordRoute: typeof ForgotpasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SupabaseCallbackRoute: typeof SupabaseCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/supabaseCallback': {
      id: '/supabaseCallback'
      path: '/supabaseCallback'
      fullPath: '/supabaseCallback'
      preLoaderRoute: typeof SupabaseCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgotpassword': {
      id: '/forgotpassword'
      path: '/forgotpassword'
      fullPath: '/forgotpassword'
      preLoaderRoute: typeof ForgotpasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emailVerify': {
      id: '/emailVerify'
      path: '/emailVerify'
      fullPath: '/emailVerify'
      preLoaderRoute: typeof EmailVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__protected': {
      id: '/__protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _protectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/LandingPage': {
      id: '/LandingPage'
      path: '/LandingPage'
      fullPath: '/LandingPage'
      preLoaderRoute: typeof LandingPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__protected/tutor': {
      id: '/__protected/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof _protectedTutorRouteImport
      parentRoute: typeof _protectedRoute
    }
    '/__protected/quizzes': {
      id: '/__protected/quizzes'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof _protectedQuizzesRouteImport
      parentRoute: typeof _protectedRoute
    }
    '/__protected/notes': {
      id: '/__protected/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof _protectedNotesRouteImport
      parentRoute: typeof _protectedRoute
    }
    '/__protected/library': {
      id: '/__protected/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof _protectedLibraryRouteImport
      parentRoute: typeof _protectedRoute
    }
    '/__protected/quizzes/': {
      id: '/__protected/quizzes/'
      path: '/'
      fullPath: '/quizzes/'
      preLoaderRoute: typeof _protectedQuizzesIndexRouteImport
      parentRoute: typeof _protectedQuizzesRoute
    }
    '/__protected/notes/': {
      id: '/__protected/notes/'
      path: '/'
      fullPath: '/notes/'
      preLoaderRoute: typeof _protectedNotesIndexRouteImport
      parentRoute: typeof _protectedNotesRoute
    }
    '/__protected/quizzes/$quizId': {
      id: '/__protected/quizzes/$quizId'
      path: '/$quizId'
      fullPath: '/quizzes/$quizId'
      preLoaderRoute: typeof _protectedQuizzesQuizIdRouteImport
      parentRoute: typeof _protectedQuizzesRoute
    }
    '/__protected/notes/$noteId': {
      id: '/__protected/notes/$noteId'
      path: '/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof _protectedNotesNoteIdRouteImport
      parentRoute: typeof _protectedNotesRoute
    }
  }
}

interface _protectedNotesRouteChildren {
  _protectedNotesNoteIdRoute: typeof _protectedNotesNoteIdRoute
  _protectedNotesIndexRoute: typeof _protectedNotesIndexRoute
}

const _protectedNotesRouteChildren: _protectedNotesRouteChildren = {
  _protectedNotesNoteIdRoute: _protectedNotesNoteIdRoute,
  _protectedNotesIndexRoute: _protectedNotesIndexRoute,
}

const _protectedNotesRouteWithChildren = _protectedNotesRoute._addFileChildren(
  _protectedNotesRouteChildren,
)

interface _protectedQuizzesRouteChildren {
  _protectedQuizzesQuizIdRoute: typeof _protectedQuizzesQuizIdRoute
  _protectedQuizzesIndexRoute: typeof _protectedQuizzesIndexRoute
}

const _protectedQuizzesRouteChildren: _protectedQuizzesRouteChildren = {
  _protectedQuizzesQuizIdRoute: _protectedQuizzesQuizIdRoute,
  _protectedQuizzesIndexRoute: _protectedQuizzesIndexRoute,
}

const _protectedQuizzesRouteWithChildren =
  _protectedQuizzesRoute._addFileChildren(_protectedQuizzesRouteChildren)

interface _protectedRouteChildren {
  _protectedLibraryRoute: typeof _protectedLibraryRoute
  _protectedNotesRoute: typeof _protectedNotesRouteWithChildren
  _protectedQuizzesRoute: typeof _protectedQuizzesRouteWithChildren
  _protectedTutorRoute: typeof _protectedTutorRoute
}

const _protectedRouteChildren: _protectedRouteChildren = {
  _protectedLibraryRoute: _protectedLibraryRoute,
  _protectedNotesRoute: _protectedNotesRouteWithChildren,
  _protectedQuizzesRoute: _protectedQuizzesRouteWithChildren,
  _protectedTutorRoute: _protectedTutorRoute,
}

const _protectedRouteWithChildren = _protectedRoute._addFileChildren(
  _protectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LandingPageRoute: LandingPageRoute,
  _protectedRoute: _protectedRouteWithChildren,
  EmailVerifyRoute: EmailVerifyRoute,
  ForgotpasswordRoute: ForgotpasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SupabaseCallbackRoute: SupabaseCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
